Algoritmo "semnome"
// Disciplina  : Algoritmos
// Autor(a)    : Gustavo de Sousa Marques
// Data atual  : 10/10/2021
Var
a, b, resultado : inteiro


Inicio
// O algoritmo recebe dois valores (um na variavel 'a' e outro na 'b')
// e sem seguida realiza a soma entre os dois e mostra o resultado na tela
escreval("Digite um numero:")
leia(a)
escreval("Digite outro numero:")
leia(b)

resultado := a + b

escreva("O resultado da soma entre os dois numeros eh")
escreva(resultado)

Fimalgoritmo