Algoritmo "semnome"
// Disciplina  : Algoritmos
// Autor(a)    : Gustavo de Sousa Marques
// Data atual  : 10/10/2021
Var
a, b : inteiro
maior : logico

Inicio
// O algoritmo recebe dois numeros e diz se eh verdadeiro ou falso que
// o primeiro numero eh maior
escreval("Escreva o primeiro numero:")
leia(a)
escreval("Escreva o segundo numero:")
leia(b)

maior := (a > b)
escreval("O primeiro numero digitado eh maior que o ultimo?")
escreval(maior)

Fimalgoritmo