Algoritmo "semnome"
// Disciplina  : Algoritmos
// Professor   : Pedro Brandao 
// Descrição   : Atividade 3.3
// Autor(a)    : Gustavo de Sousa Marques
// Data atual  : 04/10/2021
Var
LOGIC : logico
M, N : real

Inicio
escreval("Atribua valores para as variaveis a seguir:")
escreval("Digite o valor de M:")
leia(M)
escreval("Digite o valor de N:")
leia(N)

LOGIC <- (N*2) = M

escreva("A variavel LOGIC eh ", LOGIC)


Fimalgoritmo